// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuxcyewlwookgnnbinsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1eGN5ZXdsd29va2dubmJpbnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3Njk2ODQsImV4cCI6MjA1MTM0NTY4NH0.LAR8kFSBxCBs8QiKYgMW0NXWpIiaq6hyGVj8W96mOF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);